/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as access_gm_cores from "../access/gm/cores.js";
import type * as access_gm_dispatch from "../access/gm/dispatch.js";
import type * as access_gm_functions from "../access/gm/functions.js";
import type * as access_gm_operations from "../access/gm/operations.js";
import type * as access_gm_policy from "../access/gm/policy.js";
import type * as access_gm_probe from "../access/gm/probe.js";
import type * as access_gm_store from "../access/gm/store.js";
import type * as access_gm_storeAdapter from "../access/gm/storeAdapter.js";
import type * as access_identity_authEntry from "../access/identity/authEntry.js";
import type * as access_identity_functions from "../access/identity/functions.js";
import type * as access_identity_issuanceLimit from "../access/identity/issuanceLimit.js";
import type * as access_identity_operations from "../access/identity/operations.js";
import type * as access_identity_policy from "../access/identity/policy.js";
import type * as access_identity_probe from "../access/identity/probe.js";
import type * as access_identity_proofDomain from "../access/identity/proofDomain.js";
import type * as access_identity_providerAvailability from "../access/identity/providerAvailability.js";
import type * as access_identity_resolution from "../access/identity/resolution.js";
import type * as access_identity_userPolicy from "../access/identity/userPolicy.js";
import type * as access_linking_authHook from "../access/linking/authHook.js";
import type * as access_linking_ceremony from "../access/linking/ceremony.js";
import type * as access_linking_codes from "../access/linking/codes.js";
import type * as access_linking_emailChange from "../access/linking/emailChange.js";
import type * as access_linking_functions from "../access/linking/functions.js";
import type * as access_linking_operations from "../access/linking/operations.js";
import type * as access_linking_policy from "../access/linking/policy.js";
import type * as access_linking_probe from "../access/linking/probe.js";
import type * as access_linking_recovery from "../access/linking/recovery.js";
import type * as access_linking_sessionControls from "../access/linking/sessionControls.js";
import type * as access_linking_store from "../access/linking/store.js";
import type * as access_linking_storeAdapter from "../access/linking/storeAdapter.js";
import type * as access_membership_cleanup from "../access/membership/cleanup.js";
import type * as access_membership_cores from "../access/membership/cores.js";
import type * as access_membership_dispatch from "../access/membership/dispatch.js";
import type * as access_membership_functions from "../access/membership/functions.js";
import type * as access_membership_operations from "../access/membership/operations.js";
import type * as access_membership_policy from "../access/membership/policy.js";
import type * as access_membership_probe from "../access/membership/probe.js";
import type * as attention_context from "../attention/context.js";
import type * as attention_delivery_commands from "../attention/delivery/commands.js";
import type * as attention_delivery_dispatch from "../attention/delivery/dispatch.js";
import type * as attention_delivery_evaluate from "../attention/delivery/evaluate.js";
import type * as attention_delivery_executor from "../attention/delivery/executor.js";
import type * as attention_delivery_model from "../attention/delivery/model.js";
import type * as attention_delivery_operations from "../attention/delivery/operations.js";
import type * as attention_delivery_probe from "../attention/delivery/probe.js";
import type * as attention_delivery_queries from "../attention/delivery/queries.js";
import type * as attention_preferences_commands from "../attention/preferences/commands.js";
import type * as attention_preferences_dispatch from "../attention/preferences/dispatch.js";
import type * as attention_preferences_evaluation from "../attention/preferences/evaluation.js";
import type * as attention_preferences_operations from "../attention/preferences/operations.js";
import type * as attention_preferences_probe from "../attention/preferences/probe.js";
import type * as attention_preferences_queries from "../attention/preferences/queries.js";
import type * as attention_probe_shared from "../attention/probe_shared.js";
import type * as attention_push_commands from "../attention/push/commands.js";
import type * as attention_push_dispatch from "../attention/push/dispatch.js";
import type * as attention_push_executor from "../attention/push/executor.js";
import type * as attention_push_functions from "../attention/push/functions.js";
import type * as attention_push_model from "../attention/push/model.js";
import type * as attention_push_operations from "../attention/push/operations.js";
import type * as attention_push_probe from "../attention/push/probe.js";
import type * as attention_push_proofService from "../attention/push/proofService.js";
import type * as attention_push_protocol from "../attention/push/protocol.js";
import type * as attention_push_queries from "../attention/push/queries.js";
import type * as attention_read_state_commands from "../attention/read_state/commands.js";
import type * as attention_read_state_dispatch from "../attention/read_state/dispatch.js";
import type * as attention_read_state_operations from "../attention/read_state/operations.js";
import type * as attention_read_state_probe from "../attention/read_state/probe.js";
import type * as attention_read_state_queries from "../attention/read_state/queries.js";
import type * as attention_read_state_state from "../attention/read_state/state.js";
import type * as auth from "../auth.js";
import type * as calendar_connection_answers from "../calendar/connection/answers.js";
import type * as calendar_connection_cores from "../calendar/connection/cores.js";
import type * as calendar_connection_credentialStore from "../calendar/connection/credentialStore.js";
import type * as calendar_connection_dispatch from "../calendar/connection/dispatch.js";
import type * as calendar_connection_functions from "../calendar/connection/functions.js";
import type * as calendar_connection_http from "../calendar/connection/http.js";
import type * as calendar_connection_operations from "../calendar/connection/operations.js";
import type * as calendar_connection_proof from "../calendar/connection/proof.js";
import type * as calendar_connection_proofHttp from "../calendar/connection/proofHttp.js";
import type * as calendar_connection_protocol from "../calendar/connection/protocol.js";
import type * as calendar_projection_dispatch from "../calendar/projection/dispatch.js";
import type * as calendar_projection_functions from "../calendar/projection/functions.js";
import type * as calendar_projection_operations from "../calendar/projection/operations.js";
import type * as calendar_projection_proof from "../calendar/projection/proof.js";
import type * as calendar_sync_cores from "../calendar/sync/cores.js";
import type * as calendar_sync_dispatch from "../calendar/sync/dispatch.js";
import type * as calendar_sync_executor from "../calendar/sync/executor.js";
import type * as calendar_sync_functions from "../calendar/sync/functions.js";
import type * as calendar_sync_operations from "../calendar/sync/operations.js";
import type * as calendar_sync_proof from "../calendar/sync/proof.js";
import type * as calendar_sync_proofHttp from "../calendar/sync/proofHttp.js";
import type * as calendar_sync_protocol from "../calendar/sync/protocol.js";
import type * as crons from "../crons.js";
import type * as http from "../http.js";
import type * as integrations_ai_dispatch from "../integrations/ai/dispatch.js";
import type * as integrations_ai_record from "../integrations/ai/record.js";
import type * as integrations_email_copy from "../integrations/email/copy.js";
import type * as integrations_email_resend from "../integrations/email/resend.js";
import type * as integrations_email_send from "../integrations/email/send.js";
import type * as memory_extensions_catalog from "../memory/extensions/catalog.js";
import type * as memory_extensions_define from "../memory/extensions/define.js";
import type * as memory_extensions_dispatch from "../memory/extensions/dispatch.js";
import type * as memory_extensions_probe from "../memory/extensions/probe.js";
import type * as memory_extensions_references from "../memory/extensions/references.js";
import type * as memory_extensions_semantics from "../memory/extensions/semantics.js";
import type * as memory_extensions_validate from "../memory/extensions/validate.js";
import type * as memory_extensions_version from "../memory/extensions/version.js";
import type * as memory_findings_corrections from "../memory/findings/corrections.js";
import type * as memory_findings_dispatch from "../memory/findings/dispatch.js";
import type * as memory_findings_exposition from "../memory/findings/exposition.js";
import type * as memory_findings_functions from "../memory/findings/functions.js";
import type * as memory_findings_plan from "../memory/findings/plan.js";
import type * as memory_findings_prepare from "../memory/findings/prepare.js";
import type * as memory_findings_probe from "../memory/findings/probe.js";
import type * as memory_findings_publish from "../memory/findings/publish.js";
import type * as memory_findings_read from "../memory/findings/read.js";
import type * as memory_findings_references from "../memory/findings/references.js";
import type * as memory_findings_semantics from "../memory/findings/semantics.js";
import type * as memory_findings_withdrawal from "../memory/findings/withdrawal.js";
import type * as memory_recompute_executor from "../memory/recompute/executor.js";
import type * as memory_recompute_probe from "../memory/recompute/probe.js";
import type * as memory_recompute_withdrawal from "../memory/recompute/withdrawal.js";
import type * as operations_telemetry_costs from "../operations/telemetry/costs.js";
import type * as operations_telemetry_cron from "../operations/telemetry/cron.js";
import type * as operations_telemetry_emit from "../operations/telemetry/emit.js";
import type * as operations_telemetry_functions from "../operations/telemetry/functions.js";
import type * as operations_telemetry_heartbeat from "../operations/telemetry/heartbeat.js";
import type * as operations_telemetry_http from "../operations/telemetry/http.js";
import type * as operations_telemetry_incidents from "../operations/telemetry/incidents.js";
import type * as operations_telemetry_observability from "../operations/telemetry/observability.js";
import type * as operations_telemetry_proof from "../operations/telemetry/proof.js";
import type * as operations_telemetry_redact from "../operations/telemetry/redact.js";
import type * as operations_telemetry_retention from "../operations/telemetry/retention.js";
import type * as operations_telemetry_serviceToken from "../operations/telemetry/serviceToken.js";
import type * as operations_telemetry_sink from "../operations/telemetry/sink.js";
import type * as platform_context from "../platform/context.js";
import type * as platform_dispatch from "../platform/dispatch.js";
import type * as platform_echo from "../platform/echo.js";
import type * as platform_executors from "../platform/executors.js";
import type * as platform_health from "../platform/health.js";
import type * as platform_http from "../platform/http.js";
import type * as platform_jobs from "../platform/jobs.js";
import type * as platform_outbox from "../platform/outbox.js";
import type * as platform_pipeline from "../platform/pipeline.js";
import type * as platform_probe from "../platform/probe.js";
import type * as platform_publish from "../platform/publish.js";
import type * as processing_audio_executor from "../processing/audio/executor.js";
import type * as processing_audio_media from "../processing/audio/media.js";
import type * as processing_audio_orders from "../processing/audio/orders.js";
import type * as processing_audio_probe from "../processing/audio/probe.js";
import type * as processing_audio_segmentation from "../processing/audio/segmentation.js";
import type * as processing_images_commands from "../processing/images/commands.js";
import type * as processing_images_executor from "../processing/images/executor.js";
import type * as processing_images_http from "../processing/images/http.js";
import type * as processing_images_ledger from "../processing/images/ledger.js";
import type * as processing_images_probe from "../processing/images/probe.js";
import type * as processing_images_protocol from "../processing/images/protocol.js";
import type * as processing_multimodal_coverageLoader from "../processing/multimodal/coverageLoader.js";
import type * as processing_multimodal_join from "../processing/multimodal/join.js";
import type * as processing_multimodal_journal from "../processing/multimodal/journal.js";
import type * as processing_multimodal_modelStage from "../processing/multimodal/modelStage.js";
import type * as processing_multimodal_probe from "../processing/multimodal/probe.js";
import type * as processing_multimodal_publish from "../processing/multimodal/publish.js";
import type * as processing_multimodal_vision from "../processing/multimodal/vision.js";
import type * as processing_multimodal_visionOrders from "../processing/multimodal/visionOrders.js";
import type * as processing_text_analysisContext from "../processing/text/analysisContext.js";
import type * as processing_text_analyze from "../processing/text/analyze.js";
import type * as processing_text_extract from "../processing/text/extract.js";
import type * as processing_text_journal from "../processing/text/journal.js";
import type * as processing_text_probe from "../processing/text/probe.js";
import type * as projects_dispatch from "../projects/dispatch.js";
import type * as projects_functions from "../projects/functions.js";
import type * as projects_operations from "../projects/operations.js";
import type * as projects_policy from "../projects/policy.js";
import type * as projects_probe from "../projects/probe.js";
import type * as schema_shared from "../schema/shared.js";
import type * as sources_accept_acceptance from "../sources/accept/acceptance.js";
import type * as sources_accept_commands from "../sources/accept/commands.js";
import type * as sources_accept_dispatch from "../sources/accept/dispatch.js";
import type * as sources_accept_probe from "../sources/accept/probe.js";
import type * as sources_media_access_access from "../sources/media_access/access.js";
import type * as sources_media_access_commands from "../sources/media_access/commands.js";
import type * as sources_media_access_http from "../sources/media_access/http.js";
import type * as sources_media_access_probe from "../sources/media_access/probe.js";
import type * as sources_media_access_protocol from "../sources/media_access/protocol.js";
import type * as sources_probe_shared from "../sources/probe_shared.js";
import type * as sources_read_probe from "../sources/read/probe.js";
import type * as sources_read_rows from "../sources/read/rows.js";
import type * as sources_read_views from "../sources/read/views.js";
import type * as sources_uploads_acceptance_gate from "../sources/uploads/acceptance_gate.js";
import type * as sources_uploads_commands from "../sources/uploads/commands.js";
import type * as sources_uploads_dispatch from "../sources/uploads/dispatch.js";
import type * as sources_uploads_http from "../sources/uploads/http.js";
import type * as sources_uploads_ledger from "../sources/uploads/ledger.js";
import type * as sources_uploads_probe from "../sources/uploads/probe.js";
import type * as sources_uploads_protocol from "../sources/uploads/protocol.js";
import type * as work_dispatch from "../work/dispatch.js";
import type * as work_functions from "../work/functions.js";
import type * as work_operations from "../work/operations.js";
import type * as work_policy from "../work/policy.js";
import type * as work_probe from "../work/probe.js";
import type * as work_read from "../work/read.js";
import type * as work_references from "../work/references.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "access/gm/cores": typeof access_gm_cores;
  "access/gm/dispatch": typeof access_gm_dispatch;
  "access/gm/functions": typeof access_gm_functions;
  "access/gm/operations": typeof access_gm_operations;
  "access/gm/policy": typeof access_gm_policy;
  "access/gm/probe": typeof access_gm_probe;
  "access/gm/store": typeof access_gm_store;
  "access/gm/storeAdapter": typeof access_gm_storeAdapter;
  "access/identity/authEntry": typeof access_identity_authEntry;
  "access/identity/functions": typeof access_identity_functions;
  "access/identity/issuanceLimit": typeof access_identity_issuanceLimit;
  "access/identity/operations": typeof access_identity_operations;
  "access/identity/policy": typeof access_identity_policy;
  "access/identity/probe": typeof access_identity_probe;
  "access/identity/proofDomain": typeof access_identity_proofDomain;
  "access/identity/providerAvailability": typeof access_identity_providerAvailability;
  "access/identity/resolution": typeof access_identity_resolution;
  "access/identity/userPolicy": typeof access_identity_userPolicy;
  "access/linking/authHook": typeof access_linking_authHook;
  "access/linking/ceremony": typeof access_linking_ceremony;
  "access/linking/codes": typeof access_linking_codes;
  "access/linking/emailChange": typeof access_linking_emailChange;
  "access/linking/functions": typeof access_linking_functions;
  "access/linking/operations": typeof access_linking_operations;
  "access/linking/policy": typeof access_linking_policy;
  "access/linking/probe": typeof access_linking_probe;
  "access/linking/recovery": typeof access_linking_recovery;
  "access/linking/sessionControls": typeof access_linking_sessionControls;
  "access/linking/store": typeof access_linking_store;
  "access/linking/storeAdapter": typeof access_linking_storeAdapter;
  "access/membership/cleanup": typeof access_membership_cleanup;
  "access/membership/cores": typeof access_membership_cores;
  "access/membership/dispatch": typeof access_membership_dispatch;
  "access/membership/functions": typeof access_membership_functions;
  "access/membership/operations": typeof access_membership_operations;
  "access/membership/policy": typeof access_membership_policy;
  "access/membership/probe": typeof access_membership_probe;
  "attention/context": typeof attention_context;
  "attention/delivery/commands": typeof attention_delivery_commands;
  "attention/delivery/dispatch": typeof attention_delivery_dispatch;
  "attention/delivery/evaluate": typeof attention_delivery_evaluate;
  "attention/delivery/executor": typeof attention_delivery_executor;
  "attention/delivery/model": typeof attention_delivery_model;
  "attention/delivery/operations": typeof attention_delivery_operations;
  "attention/delivery/probe": typeof attention_delivery_probe;
  "attention/delivery/queries": typeof attention_delivery_queries;
  "attention/preferences/commands": typeof attention_preferences_commands;
  "attention/preferences/dispatch": typeof attention_preferences_dispatch;
  "attention/preferences/evaluation": typeof attention_preferences_evaluation;
  "attention/preferences/operations": typeof attention_preferences_operations;
  "attention/preferences/probe": typeof attention_preferences_probe;
  "attention/preferences/queries": typeof attention_preferences_queries;
  "attention/probe_shared": typeof attention_probe_shared;
  "attention/push/commands": typeof attention_push_commands;
  "attention/push/dispatch": typeof attention_push_dispatch;
  "attention/push/executor": typeof attention_push_executor;
  "attention/push/functions": typeof attention_push_functions;
  "attention/push/model": typeof attention_push_model;
  "attention/push/operations": typeof attention_push_operations;
  "attention/push/probe": typeof attention_push_probe;
  "attention/push/proofService": typeof attention_push_proofService;
  "attention/push/protocol": typeof attention_push_protocol;
  "attention/push/queries": typeof attention_push_queries;
  "attention/read_state/commands": typeof attention_read_state_commands;
  "attention/read_state/dispatch": typeof attention_read_state_dispatch;
  "attention/read_state/operations": typeof attention_read_state_operations;
  "attention/read_state/probe": typeof attention_read_state_probe;
  "attention/read_state/queries": typeof attention_read_state_queries;
  "attention/read_state/state": typeof attention_read_state_state;
  auth: typeof auth;
  "calendar/connection/answers": typeof calendar_connection_answers;
  "calendar/connection/cores": typeof calendar_connection_cores;
  "calendar/connection/credentialStore": typeof calendar_connection_credentialStore;
  "calendar/connection/dispatch": typeof calendar_connection_dispatch;
  "calendar/connection/functions": typeof calendar_connection_functions;
  "calendar/connection/http": typeof calendar_connection_http;
  "calendar/connection/operations": typeof calendar_connection_operations;
  "calendar/connection/proof": typeof calendar_connection_proof;
  "calendar/connection/proofHttp": typeof calendar_connection_proofHttp;
  "calendar/connection/protocol": typeof calendar_connection_protocol;
  "calendar/projection/dispatch": typeof calendar_projection_dispatch;
  "calendar/projection/functions": typeof calendar_projection_functions;
  "calendar/projection/operations": typeof calendar_projection_operations;
  "calendar/projection/proof": typeof calendar_projection_proof;
  "calendar/sync/cores": typeof calendar_sync_cores;
  "calendar/sync/dispatch": typeof calendar_sync_dispatch;
  "calendar/sync/executor": typeof calendar_sync_executor;
  "calendar/sync/functions": typeof calendar_sync_functions;
  "calendar/sync/operations": typeof calendar_sync_operations;
  "calendar/sync/proof": typeof calendar_sync_proof;
  "calendar/sync/proofHttp": typeof calendar_sync_proofHttp;
  "calendar/sync/protocol": typeof calendar_sync_protocol;
  crons: typeof crons;
  http: typeof http;
  "integrations/ai/dispatch": typeof integrations_ai_dispatch;
  "integrations/ai/record": typeof integrations_ai_record;
  "integrations/email/copy": typeof integrations_email_copy;
  "integrations/email/resend": typeof integrations_email_resend;
  "integrations/email/send": typeof integrations_email_send;
  "memory/extensions/catalog": typeof memory_extensions_catalog;
  "memory/extensions/define": typeof memory_extensions_define;
  "memory/extensions/dispatch": typeof memory_extensions_dispatch;
  "memory/extensions/probe": typeof memory_extensions_probe;
  "memory/extensions/references": typeof memory_extensions_references;
  "memory/extensions/semantics": typeof memory_extensions_semantics;
  "memory/extensions/validate": typeof memory_extensions_validate;
  "memory/extensions/version": typeof memory_extensions_version;
  "memory/findings/corrections": typeof memory_findings_corrections;
  "memory/findings/dispatch": typeof memory_findings_dispatch;
  "memory/findings/exposition": typeof memory_findings_exposition;
  "memory/findings/functions": typeof memory_findings_functions;
  "memory/findings/plan": typeof memory_findings_plan;
  "memory/findings/prepare": typeof memory_findings_prepare;
  "memory/findings/probe": typeof memory_findings_probe;
  "memory/findings/publish": typeof memory_findings_publish;
  "memory/findings/read": typeof memory_findings_read;
  "memory/findings/references": typeof memory_findings_references;
  "memory/findings/semantics": typeof memory_findings_semantics;
  "memory/findings/withdrawal": typeof memory_findings_withdrawal;
  "memory/recompute/executor": typeof memory_recompute_executor;
  "memory/recompute/probe": typeof memory_recompute_probe;
  "memory/recompute/withdrawal": typeof memory_recompute_withdrawal;
  "operations/telemetry/costs": typeof operations_telemetry_costs;
  "operations/telemetry/cron": typeof operations_telemetry_cron;
  "operations/telemetry/emit": typeof operations_telemetry_emit;
  "operations/telemetry/functions": typeof operations_telemetry_functions;
  "operations/telemetry/heartbeat": typeof operations_telemetry_heartbeat;
  "operations/telemetry/http": typeof operations_telemetry_http;
  "operations/telemetry/incidents": typeof operations_telemetry_incidents;
  "operations/telemetry/observability": typeof operations_telemetry_observability;
  "operations/telemetry/proof": typeof operations_telemetry_proof;
  "operations/telemetry/redact": typeof operations_telemetry_redact;
  "operations/telemetry/retention": typeof operations_telemetry_retention;
  "operations/telemetry/serviceToken": typeof operations_telemetry_serviceToken;
  "operations/telemetry/sink": typeof operations_telemetry_sink;
  "platform/context": typeof platform_context;
  "platform/dispatch": typeof platform_dispatch;
  "platform/echo": typeof platform_echo;
  "platform/executors": typeof platform_executors;
  "platform/health": typeof platform_health;
  "platform/http": typeof platform_http;
  "platform/jobs": typeof platform_jobs;
  "platform/outbox": typeof platform_outbox;
  "platform/pipeline": typeof platform_pipeline;
  "platform/probe": typeof platform_probe;
  "platform/publish": typeof platform_publish;
  "processing/audio/executor": typeof processing_audio_executor;
  "processing/audio/media": typeof processing_audio_media;
  "processing/audio/orders": typeof processing_audio_orders;
  "processing/audio/probe": typeof processing_audio_probe;
  "processing/audio/segmentation": typeof processing_audio_segmentation;
  "processing/images/commands": typeof processing_images_commands;
  "processing/images/executor": typeof processing_images_executor;
  "processing/images/http": typeof processing_images_http;
  "processing/images/ledger": typeof processing_images_ledger;
  "processing/images/probe": typeof processing_images_probe;
  "processing/images/protocol": typeof processing_images_protocol;
  "processing/multimodal/coverageLoader": typeof processing_multimodal_coverageLoader;
  "processing/multimodal/join": typeof processing_multimodal_join;
  "processing/multimodal/journal": typeof processing_multimodal_journal;
  "processing/multimodal/modelStage": typeof processing_multimodal_modelStage;
  "processing/multimodal/probe": typeof processing_multimodal_probe;
  "processing/multimodal/publish": typeof processing_multimodal_publish;
  "processing/multimodal/vision": typeof processing_multimodal_vision;
  "processing/multimodal/visionOrders": typeof processing_multimodal_visionOrders;
  "processing/text/analysisContext": typeof processing_text_analysisContext;
  "processing/text/analyze": typeof processing_text_analyze;
  "processing/text/extract": typeof processing_text_extract;
  "processing/text/journal": typeof processing_text_journal;
  "processing/text/probe": typeof processing_text_probe;
  "projects/dispatch": typeof projects_dispatch;
  "projects/functions": typeof projects_functions;
  "projects/operations": typeof projects_operations;
  "projects/policy": typeof projects_policy;
  "projects/probe": typeof projects_probe;
  "schema/shared": typeof schema_shared;
  "sources/accept/acceptance": typeof sources_accept_acceptance;
  "sources/accept/commands": typeof sources_accept_commands;
  "sources/accept/dispatch": typeof sources_accept_dispatch;
  "sources/accept/probe": typeof sources_accept_probe;
  "sources/media_access/access": typeof sources_media_access_access;
  "sources/media_access/commands": typeof sources_media_access_commands;
  "sources/media_access/http": typeof sources_media_access_http;
  "sources/media_access/probe": typeof sources_media_access_probe;
  "sources/media_access/protocol": typeof sources_media_access_protocol;
  "sources/probe_shared": typeof sources_probe_shared;
  "sources/read/probe": typeof sources_read_probe;
  "sources/read/rows": typeof sources_read_rows;
  "sources/read/views": typeof sources_read_views;
  "sources/uploads/acceptance_gate": typeof sources_uploads_acceptance_gate;
  "sources/uploads/commands": typeof sources_uploads_commands;
  "sources/uploads/dispatch": typeof sources_uploads_dispatch;
  "sources/uploads/http": typeof sources_uploads_http;
  "sources/uploads/ledger": typeof sources_uploads_ledger;
  "sources/uploads/probe": typeof sources_uploads_probe;
  "sources/uploads/protocol": typeof sources_uploads_protocol;
  "work/dispatch": typeof work_dispatch;
  "work/functions": typeof work_functions;
  "work/operations": typeof work_operations;
  "work/policy": typeof work_policy;
  "work/probe": typeof work_probe;
  "work/read": typeof work_read;
  "work/references": typeof work_references;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
};
