/**
 * Typed id convention for Kiero.
 *
 * Two id families exist:
 *
 * - **Document ids** are generated by Convex for a row of one table. They are
 *   represented as branded strings keyed by the table name
 *   (`TableId<"companies">` is not assignable to `TableId<"tasks">`), so a
 *   mistyped reference is a compile error. The closed `TableIdName` union is
 *   the table inventory owned by the modular schema fragments; a new table is
 *   a coordinated change to this file and its fragment.
 * - **Generated ids** (domain event ids, correlation ids, idempotency keys)
 *   are produced by Kiero code before any row exists. They are branded UUID
 *   values created through `newX` helpers below. Constructing them always
 *   goes through the schema (never a cast), so an invalid value cannot enter.
 *
 * Certified by A3 on 2026-09-09 (docs/implementation/contracts/README.md).
 */

import { Schema } from "effect";

/**
 * The closed table inventory of the modular Convex schema, as a runtime
 * constant. `convex/schema.ts` checks its composition against this list, so
 * a fragment table without an inventory entry (or the reverse) fails loudly.
 */
export const TABLE_ID_NAMES = [
  // access/identity
  "users",
  "sessions",
  // access/identity: Convex Auth provider tables (B1 amendment; the library
  // owns their shape, the identity fragment registers them in the schema)
  "authSessions",
  "authAccounts",
  "authRefreshTokens",
  "authVerificationCodes",
  "authVerifiers",
  "authRateLimits",
  // access/membership
  "companies",
  "memberships",
  "invitations",
  // access/gm
  "gmAccessGrants",
  // access/gm (B4 amendment): the per-company alpha participation authority
  // an open grant depends on (activation open = the firm is a testing firm).
  "gmCompanyActivations",
  // access/linking (B2: verified linking ceremonies, email changes,
  // manual-recovery ledger)
  "linkingAttempts",
  "emailChangeRequests",
  "accountRecoveries",
  // projects
  "contacts",
  "contactRoles",
  "projects",
  "projectAliases",
  // sources/accept
  "sources",
  "sourceProjectLinks",
  "extractions",
  "sourceFragments",
  // sources/uploads
  "uploads",
  "attachments",
  "mediaRepresentations",
  // processing/audio (D6 amendment, flagged in the issue report): the
  // resumable long-audio STT fragment - transcript orders and per-segment
  // checkpoints over accepted audio attachments.
  "audioTranscripts",
  "audioSegments",
  // memory/findings
  "findings",
  "findingRevisions",
  "evidenceLinks",
  "findingDependencies",
  "changeSets",
  "publicationGroups",
  "clarifications",
  // memory/extensions
  "extensionDefinitions",
  "extensionVersions",
  "extensionUsage",
  // work
  "tasks",
  "checklistItems",
  "events",
  // C4 amendment (flagged, I2 precedent): the immutable change history of
  // tasks, checklist items and events - actor, time and evidence basis per
  // change (issue #27 acceptance: "immutable history").
  "workRevisions",
  // platform (durable execution + outbox)
  "processingRuns",
  "processingSteps",
  "processingAttempts",
  // processing/multimodal (E4 amendment, flagged coordinated change, the
  // D6 precedent): the vision-extraction order rows over retained image
  // representations (issue #38).
  "visionOrders",
  "durableJobs",
  "outboxEvents",
  // A3 certification amendment: observable external-effect ledger used by the
  // no-duplicate-effect proof (the echo stand-in for external systems).
  "externalEffects",
  // attention/read-state
  "readStates",
  // attention/preferences
  "notificationPreferences",
  // attention/delivery
  "notificationIntents",
  "pushSubscriptions",
  "notificationAttempts",
  // attention/push (F3 amendment, the G3 closed-inventory precedent): the
  // per-device delivery rows of the web push transport, plus the guarded
  // proof-only fake push service device store.
  "pushDeliveries",
  "pushProofDevices",
  // attention/reminders (F4 amendment, flagged): the per-task schedule
  // anchor and the personal per-task snoozes ("Odroczenie przypomnień").
  "reminderSchedules",
  "reminderSnoozes",
  // calendar/connection
  "calendarConnections",
  // calendar/projection
  "calendarCopies",
  "calendarSyncState",
  // calendar/sync (G3 amendment, the G1/G2 closed-inventory precedent):
  // the per-leg attempt/outcome ledger, and the proof-only fake-Google
  // event store the guarded fixtures write.
  "calendarSyncAttempts",
  "calendarProofEvents",
  // operations/exports
  "exports",
  "exportSourceLinks",
  // operations/deletion
  "deletionRecords",
  // I4 amendment (issue #56, flagged in the issue report; the F3/G3
  // closed-inventory precedent): the per-stage purge tracking rows of one
  // permanent deletion (media bytes, transcripts, findings marking, search
  // index, notification work, exports) - pending/purged/failed state with
  // the 24-hour deadline the administrator's status screen reports.
  "deletionPurgeStages",
  // operations/backups
  "recoveryManifests",
  // operations/telemetry
  "auditRecords",
  "diagnosticEvents",
  // I2 amendments: heartbeat ledger (backend-silence detection) and the
  // all-in cost accounting behind the 400/500 PLN alerts.
  "healthHeartbeats",
  "costEntries",
  "costAlertStates",
  // search
  "searchEntries",
  "searchIndexGenerations",
] as const;

/** The closed table inventory (derived from the runtime constant). */
export type TableIdName = (typeof TABLE_ID_NAMES)[number];

/**
 * The closed set of tables a revision expectation or conflict reference may
 * name. The `satisfies` check ties every member to the live table inventory:
 * renaming or removing one of these tables breaks compilation here instead
 * of silently accepting dead names.
 */
const EXPECTED_RECORD_TABLES = [
  "findings",
  "tasks",
  "checklistItems",
  "events",
  "projects",
  "sources",
  "extensionDefinitions",
  "clarifications",
] as const satisfies readonly TableIdName[];

export const ExpectedRecordTable = Schema.Literals(EXPECTED_RECORD_TABLES);
export type ExpectedRecordTable = Schema.Schema.Type<typeof ExpectedRecordTable>;

/**
 * The branded schema for one table's document ids. Instantiated with a
 * literal table name it yields a nominally distinct string type.
 */
export const tableIdSchema = <T extends TableIdName>(table: T) =>
  Schema.String.pipe(Schema.brand(table));

/** The branded document id type of one table. */
export type TableId<T extends TableIdName> = Schema.Schema.Type<
  ReturnType<typeof tableIdSchema<T>>
>;

/**
 * Normalizes an unknown value into a branded table id without a cast.
 *
 * This checks only that the value is a string; it does NOT prove the id
 * exists in the table or that the string is a well-formed Convex id:
 * Convex generates ids and validates them server-side (`ctx.db.normalizeId`),
 * which is part of the A3 runtime proof. The brand ties the reference to one
 * table so cross-table misuse fails to compile.
 */
export function parseTableId<T extends TableIdName>(
  table: T,
  value: unknown,
): TableId<T> | null {
  const decoded = Schema.decodeUnknownOption(tableIdSchema(table))(value);
  return decoded._tag === "Some" ? decoded.value : null;
}

// Load-bearing document id aliases (English table names; see CONTEXT.md for
// the Polish domain terms these records carry).

export type UserId = TableId<"users">;
export type SessionId = TableId<"sessions">;
export type CompanyId = TableId<"companies">;
export type MembershipId = TableId<"memberships">;
export type InvitationId = TableId<"invitations">;
export type ContactId = TableId<"contacts">;
export type ProjectId = TableId<"projects">;
export type SourceId = TableId<"sources">;
export type UploadId = TableId<"uploads">;
export type AttachmentId = TableId<"attachments">;
export type MediaRepresentationId = TableId<"mediaRepresentations">;
export type ExtractionId = TableId<"extractions">;
export type SourceFragmentId = TableId<"sourceFragments">;
export type FindingId = TableId<"findings">;
export type FindingRevisionId = TableId<"findingRevisions">;
export type ChangeSetId = TableId<"changeSets">;
export type ClarificationId = TableId<"clarifications">;
export type ExtensionDefinitionId = TableId<"extensionDefinitions">;
export type ExtensionVersionId = TableId<"extensionVersions">;
export type TaskId = TableId<"tasks">;
export type ChecklistItemId = TableId<"checklistItems">;
/** Id of a work `events` row ("Zdarzenie"), not of a domain event. */
export type WorkEventId = TableId<"events">;
export type ProcessingRunId = TableId<"processingRuns">;
export type NotificationIntentId = TableId<"notificationIntents">;
export type PushDeliveryId = TableId<"pushDeliveries">;
export type CalendarConnectionId = TableId<"calendarConnections">;
export type CalendarCopyId = TableId<"calendarCopies">;
export type ExportId = TableId<"exports">;

// Generated identifiers (created by Kiero code, not by Convex). Each is a
// UUID validated and branded through its own schema; construction always
// decodes through the schema, so a malformed value cannot exist.

/** Id of one emitted domain event (outbox row identity). */
export const EventIdSchema = Schema.String.pipe(
  Schema.check(Schema.isUUID()),
  Schema.brand("EventId"),
);
export type EventId = Schema.Schema.Type<typeof EventIdSchema>;

/** Correlation id threading one user/agent interaction through commands, jobs and events. */
export const CorrelationIdSchema = Schema.String.pipe(
  Schema.check(Schema.isUUID()),
  Schema.brand("CorrelationId"),
);
export type CorrelationId = Schema.Schema.Type<typeof CorrelationIdSchema>;

/** Client-chosen idempotency key for a command; `idem_` + uuid. */
export const IdempotencyKeySchema = Schema.String.pipe(
  Schema.check(Schema.isPattern(/^idem_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)),
  Schema.brand("IdempotencyKey"),
);
export type IdempotencyKey = Schema.Schema.Type<typeof IdempotencyKeySchema>;

/** Id of a durable job registration; `job_` + uuid. */
export const DurableJobKeySchema = Schema.String.pipe(
  Schema.check(Schema.isPattern(/^job_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)),
  Schema.brand("DurableJobKey"),
);
export type DurableJobKey = Schema.Schema.Type<typeof DurableJobKeySchema>;

function newGeneratedUuid(): string {
  return crypto.randomUUID();
}

/** Generates a fresh domain event id (decode through the schema, no casts). */
export function newEventId(): EventId {
  return Schema.decodeUnknownSync(EventIdSchema)(newGeneratedUuid());
}

/** Generates a fresh correlation id. */
export function newCorrelationId(): CorrelationId {
  return Schema.decodeUnknownSync(CorrelationIdSchema)(newGeneratedUuid());
}

/** Generates a fresh idempotency key. */
export function newIdempotencyKey(): IdempotencyKey {
  return Schema.decodeUnknownSync(IdempotencyKeySchema)(`idem_${newGeneratedUuid()}`);
}

/** Generates a fresh durable job key. */
export function newDurableJobKey(): DurableJobKey {
  return Schema.decodeUnknownSync(DurableJobKeySchema)(`job_${newGeneratedUuid()}`);
}
