#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: owner-held credentials for the Kiero Convex deployments.
# Values go straight to `convex env set` over stdin: never to a file, never
# echoed. Run from the repo root: bash infra/environments/owner-credentials.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

CONVEX=(npx --yes convex@1.45.0)
STAGING="wojtek-piskorz-jr:kiero-dev-core:staging"
DEV="glorious-hawk-339"
STAGING_SITE="https://outgoing-marlin-429.eu-west-1.convex.site"
TARGETS=("$STAGING")
SET_ON=()   # "NAME@deployment" pairs written this run

# present NAME DEPLOYMENT: true when the variable already exists (names only).
present() {
  "${CONVEX[@]}" env list --names-only --deployment "$2" 2>/dev/null | grep -qx "$1"
}

# present_everywhere NAME: true when every selected target already has it.
present_everywhere() {
  local target
  for target in "${TARGETS[@]}"; do present "$1" "$target" || return 1; done
}

# convex_set NAME VALUE [only-deployment]: sets the value over stdin.
convex_set() {
  local name="$1" value="$2" target
  local targets=("${TARGETS[@]}")
  [[ $# -ge 3 ]] && targets=("$3")
  if [[ -z "$value" ]]; then
    SKIPPED+=("$name (no value entered)")
    warn "no value for $name; skipped"
    return
  fi
  for target in "${targets[@]}"; do
    if printf '%s' "$value" | "${CONVEX[@]}" env set "$name" --deployment "$target" >/dev/null 2>&1; then
      SET_ON+=("$name@$target")
      printf '  %s✓ set%s %s on %s\n' "$GREEN" "$RESET" "$name" "$target"
    else
      SKIPPED+=("$name on $target (convex env set failed; is the CLI logged in?)")
      warn "could not set $name on $target"
    fi
  done
}

# set_staging_secret NAME VALUE: GitHub `staging` environment secret the
# release injects into the Workers.
set_staging_secret() {
  if printf '%s' "$2" | gh secret set "$1" --env staging >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$1")
    printf '  %s✓ set%s GitHub staging secret %s\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("GitHub staging secret $1 (gh secret set $1 --env staging)")
    warn "could not set GitHub staging secret $1"
  fi
}

# keep_or_ask NAME "prompt" [secret|plain]: offers to keep an existing value.
keep_or_ask() {
  local name="$1" prompt="$2" kind="${3:-secret}"
  if present_everywhere "$name" && confirm "$name is already set on every target. Keep it?"; then
    printf -v "$name" '%s' ""
    note "kept $name"
    return 1
  fi
  if [[ "$kind" == "secret" ]]; then ask_secret "$name" "$prompt"; else ask "$name" "$prompt"; fi
  return 0
}

banner "Kiero: owner credentials for Convex"

stage "Targets and tools"
say "Staging always gets these values. Dev is optional: AI keys there mean"
say "local experiments spend real tokens."
step "Checking the Convex CLI login and GitHub CLI…"
if "${CONVEX[@]}" env list --names-only --deployment "$STAGING" >/dev/null 2>&1; then
  note "Convex CLI can read staging."
else
  warn "The Convex CLI cannot read staging. Run: npx --yes convex@1.45.0 login"
  pause "Press Enter after logging in"
fi
gh auth status >/dev/null 2>&1 || warn "gh is not logged in; the Axiom GitHub secret will be skipped."
if confirm "Also set the same values on dev ($DEV)?"; then TARGETS+=("$DEV"); fi
note "targets: ${TARGETS[*]}"
pause

stage "DeepSeek (chat and vision)"
open_url "https://platform.deepseek.com/api_keys"
step "Create API key → name it 'kiero' → copy the key (shown once)."
if keep_or_ask DEEPSEEK_API_KEY "Paste the DeepSeek API key:"; then
  convex_set DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"
fi
pause

stage "OpenRouter (transcription, embeddings, fallback)"
open_url "https://openrouter.ai/settings/keys"
step "Create Key → name it 'kiero' → optionally set a credit limit → copy."
if keep_or_ask OPENROUTER_API_KEY "Paste the OpenRouter API key:"; then
  convex_set OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
fi
pause

stage "Resend (sign-in codes and invitations)"
open_url "https://resend.com/api-keys"
step "Create API Key → permission 'Sending access' → copy."
if keep_or_ask RESEND_API_KEY "Paste the Resend API key:"; then
  convex_set RESEND_API_KEY "$RESEND_API_KEY"
fi
say ""
say "Sender address: a verified domain sender such as 'Kiero <kiero@your-domain>'."
note "Leave empty to keep the Resend sandbox sender (it only delivers to your own address)."
if keep_or_ask RESEND_FROM "Sender (Name <address>):" plain && [[ -n "${RESEND_FROM:-}" ]]; then
  convex_set RESEND_FROM "$RESEND_FROM"
fi
pause

stage "Google sign-in (staging OAuth client)"
say "Staging moved to a new Convex deployment, so the OAuth client must allow"
say "its callback addresses."
open_url "https://console.cloud.google.com/apis/credentials?project=kiero-508611"
step "OAuth 2.0 Client IDs → open the staging web client."
step "Authorized redirect URIs → add both, then Save:"
note "  $STAGING_SITE/api/auth/callback/google"
note "  $STAGING_SITE/calendar/oauth/callback"
step "Copy the Client ID. For the secret, copy an existing one or 'Add secret'."
note "Only staging gets these; dev sign-in uses email codes."
if keep_or_ask AUTH_GOOGLE_ID "Paste the Client ID:" plain; then
  convex_set AUTH_GOOGLE_ID "$AUTH_GOOGLE_ID" "$STAGING"
fi
if keep_or_ask AUTH_GOOGLE_SECRET "Paste the Client secret:"; then
  convex_set AUTH_GOOGLE_SECRET "$AUTH_GOOGLE_SECRET" "$STAGING"
fi
pause

stage "Axiom (diagnostics)"
open_url "https://app.axiom.co/"
step "Settings → API tokens → New token → ingest-only on dataset 'kiero-staging' → copy."
if keep_or_ask AXIOM_API_TOKEN "Paste the Axiom ingest token:"; then
  convex_set AXIOM_API_TOKEN "$AXIOM_API_TOKEN" "$STAGING"
  # The release injects this one into the Workers.
  set_staging_secret STAGING_AXIOM_API_TOKEN "$AXIOM_API_TOKEN"
fi
pause

stage "GM operators"
say "Addresses allowed to enter the audited GM mode (comma-separated)."
if keep_or_ask KIERO_GM_EMAILS "GM email address(es):" plain; then
  convex_set KIERO_GM_EMAILS "$KIERO_GM_EMAILS"
fi
pause

stage "Verify"
step "Missing variables per deployment (names only):"
node infra/environments/provision-runtime.mjs --target staging | grep -E "owner-provided" || true
if [[ " ${TARGETS[*]} " == *" $DEV "* ]]; then
  node infra/environments/provision-runtime.mjs --target dev | grep -E "owner-provided" || true
fi
if [[ " ${WRITTEN_SECRET[*]} " == *" STAGING_AXIOM_API_TOKEN "* ]]; then
  say ""
  warn "Workers read the Axiom token only after a release:"
  note "  gh workflow run release.yml --ref main -f target=staging -f notes='Axiom token'"
fi
pause

finish
if (( ${#SET_ON[@]} )); then
  note "set ${#SET_ON[@]} Convex variable(s): ${SET_ON[*]}"
  printf '\n'
fi
