/**
 * R8 focused tests (#167): serving the qualification PWA through Workers
 * Static Assets. Deterministic only: no cloud is contacted, nothing is
 * deployed, no credentials are read. The suite proves:
 *
 * - the web Worker config (apps/web/wrangler.jsonc) declares explicit
 *   dev/staging/alpha names, serves the existing Vite output with
 *   single-page-application fallback, and is static-assets-only (no main,
 *   no bindings, no Container);
 * - the pinned wrangler validates the static-only Worker for the staging
 *   env WITHOUT any Container (dry-run);
 * - a local wrangler dev server actually serves direct links to /zrodlo,
 *   /praca and /co-teraz through the SPA fallback and delivers /sw.js
 *   byte-for-byte (never the HTML shell);
 * - through the release boundary (the checked adapter + the committed
 *   staging descriptor) a web build missing VITE_CONVEX_URL or
 *   VITE_GATEWAY_URL refuses to start any transport, and a wrong
 *   environment label refuses everything;
 * - the wrangler-deploy transport the web component rides on refuses an
 *   identity that does not name the declared worker (PATH-shimmed npx).
 */

import { describe, expect, it, beforeAll, afterAll } from "vitest";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  openSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join } from "node:path";
import { pathToFileURL } from "node:url";
import { fileURLToPath } from "node:url";
import { spawn, spawnSync } from "node:child_process";
import net from "node:net";

const repoRoot = fileURLToPath(new URL("../..", import.meta.url));
const webApp = join(repoRoot, "apps", "web");
const webConfigPath = join(webApp, "wrangler.jsonc");
const gatewayConfigPath = join(repoRoot, "apps", "gateway", "wrangler.jsonc");
const stagingDescriptorPath = join(repoRoot, "infra", "release", "targets", "staging.json");
const releaseWorkflowPath = join(repoRoot, ".github", "workflows", "release.yml");
const adapterCli = join(repoRoot, "infra", "release", "deploy-component.mjs");
const CHECKS_JOB_NAME = "npm ci, typecheck, test, build (Node 22.22.3)";
const REVISION = "3333333333333333333333333333333333333333";
const STAGING_WEB_ORIGIN = "https://kiero-staging-web.wojtek-524.workers.dev";

/** Strips line and block comments, then strict JSON (the shape-check recipe). */
function parseJsonc(text: string): Record<string, unknown> {
  const stripped = text
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|[^:"'\\])\/\/.*$/gm, "$1");
  return JSON.parse(stripped) as Record<string, unknown>;
}

interface WebConfig {
  name?: string;
  main?: string;
  vars?: unknown;
  account_id?: string;
  containers?: unknown[];
  r2_buckets?: unknown[];
  assets?: { directory?: string; not_found_handling?: string };
  env?: Record<string, { name?: string }>;
}

const webConfig = parseJsonc(readFileSync(webConfigPath, "utf8")) as WebConfig;
const gatewayConfig = parseJsonc(readFileSync(gatewayConfigPath, "utf8")) as unknown as {
  env?: Record<string, { vars?: Record<string, string> }>;
};
const stagingDescriptor = JSON.parse(readFileSync(stagingDescriptorPath, "utf8")) as {
  components: Array<{
    id: string;
    build: string | null;
    artifact: string;
    transport: { kind: string; cwd?: string; wranglerEnv?: string; workerName?: string; projectName?: string };
    requiredConfig: string[];
  }>;
};
const webComponent = stagingDescriptor.components.find((component) => component.id === "web");
const releaseWorkflow = readFileSync(releaseWorkflowPath, "utf8");

// ---------------------------------------------------------------------------
// The local fixture bundle: exact bytes the serving checks assert against.
// dist/ is a disposable gitignored build output (regenerated by
// `npm run build --workspace @kiero/web`), so the suite may own it for the
// duration of the run and removes it (and wrangler's local state) afterwards.
// ---------------------------------------------------------------------------

const FIXTURE_TITLE = "Kiero-r8-static-assets-fixture";
const FIXTURE_SW = "// Kiero r8 fixture service worker (sw.js delivery proof)";
const FIXTURE_ASSET_NAME = "r8-fixture-asset.txt";
const FIXTURE_ASSET_BYTES = "kiero-r8-fixture-bytes";
const distDir = join(webApp, "dist");

function writeFixtureDist() {
  // Own the output directory outright (any stale build or manual run would
  // otherwise change the file count the dry-run reports).
  rmSync(distDir, { recursive: true, force: true });
  mkdirSync(distDir, { recursive: true });
  writeFileSync(
    join(distDir, "index.html"),
    `<!doctype html><html lang="pl"><head><meta charset="UTF-8"><title>${FIXTURE_TITLE}</title></head><body><div id="root"></div></body></html>`,
  );
  writeFileSync(join(distDir, "sw.js"), FIXTURE_SW);
  writeFileSync(join(distDir, FIXTURE_ASSET_NAME), FIXTURE_ASSET_BYTES);
}

function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      if (address === null || typeof address === "string") {
        server.close(() => reject(new Error("no free port")));
        return;
      }
      const { port } = address;
      server.close(() => resolve(port));
    });
  });
}

async function fetchUntilReady(url: string, attempts = 60): Promise<Response> {
  let lastError = "server never became ready";
  for (let attempt = 0; attempt < attempts; attempt += 1) {
    try {
      const response = await fetch(url, { signal: AbortSignal.timeout(2000) });
      if (response.status === 200) return response;
      lastError = `status ${String(response.status)}`;
    } catch (error) {
      lastError = error instanceof Error ? error.message : String(error);
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }
  throw new Error(`${url} never became ready (${lastError})`);
}

/** One wrangler dev server bound to localhost for the whole describe block. */
let devServer: { process: ReturnType<typeof spawn>; port: number } | null = null;

async function startDevServer() {
  const port = await freePort();
  const logFile = join(tmpdir(), `kiero-r8-wrangler-dev-${Date.now()}.log`);
  const log = openSync(logFile, "a");
  const child = spawn("npx", ["wrangler", "dev", "--port", String(port), "--ip", "127.0.0.1"], {
    cwd: webApp,
    env: {
      PATH: process.env.PATH ?? "",
      CI: "true",
      NO_COLOR: "1",
      WRANGLER_SEND_METRICS: "false",
    },
    stdio: ["ignore", log, log],
    detached: true, // own process group: kill takes workerd down with wrangler
  });
  await fetchUntilReady(`http://127.0.0.1:${String(port)}/`).catch((cause: unknown) => {
    // Readiness failed: the child is still detached and unowned (devServer
    // is only assigned after this resolves), so kill the process group HERE
    // or a failed startup leaks wrangler + workerd holding the port.
    try {
      if (child.pid !== undefined) process.kill(-child.pid, "SIGKILL");
    } catch {
      child.kill("SIGKILL");
    }
    throw cause;
  });
  return { process: child, port };
}

beforeAll(() => {
  writeFixtureDist();
}, 30_000);

afterAll(() => {
  // Static-assets Worker checks leave only disposable local state.
  rmSync(distDir, { recursive: true, force: true });
  rmSync(join(webApp, ".wrangler"), { recursive: true, force: true });
}, 30_000);

describe("R8 config: explicit names, Vite output, SPA fallback, static-only", () => {
  it("declares the dev default plus staging and alpha web Worker names", () => {
    expect(webConfig.name).toBe("kiero-dev-web");
    expect(webConfig.env?.staging?.name).toBe("kiero-staging-web");
    expect(webConfig.env?.["alpha-production"]?.name).toBe("kiero-alpha-web");
    expect(webConfig.account_id).toBeUndefined();
  });

  it("serves the existing Vite output with single-page-application fallback", () => {
    expect(webConfig.assets?.directory).toBe("./dist");
    expect(webConfig.assets?.not_found_handling).toBe("single-page-application");
  });

  it("is static-assets-only: no main, no vars, no bindings, no containers", () => {
    expect(webConfig.main).toBeUndefined();
    expect(webConfig.vars).toBeUndefined();
    expect(webConfig.r2_buckets ?? []).toHaveLength(0);
    expect(webConfig.containers ?? []).toHaveLength(0);
  });

  it("the gateway staging CORS allow-list pins exactly the static-assets origin", () => {
    const stagingVars = gatewayConfig.env?.staging?.vars ?? {};
    expect(stagingVars.ALLOWED_APP_ORIGINS).toBe(STAGING_WEB_ORIGIN);
    // dev and alpha keep their current shape: no staging origin leaks there.
    expect(gatewayConfig.env?.["alpha-production"]?.vars?.ALLOWED_APP_ORIGINS).toBeUndefined();
  });
});

describe("R8 descriptor: the staging release deploys the web Worker, not Pages", () => {
  it("the web component rides the checked wrangler-deploy transport", () => {
    if (webComponent === undefined) throw new Error("staging descriptor has no web component");
    expect(webComponent.transport).toEqual({
      kind: "wrangler-deploy",
      cwd: "apps/web",
      wranglerEnv: "staging",
      workerName: "kiero-staging-web",
    });
    // The declared worker is exactly the config's staging env name: the
    // transport's identity check and the config cannot drift apart.
    expect(webComponent.transport.workerName).toBe(webConfig.env?.staging?.name);
    // No staging component deploys Pages anymore.
    expect(stagingDescriptor.components.some((c) => c.transport.kind === "wrangler-pages")).toBe(false);
  });

  it("builds the pinned Vite output and requires both public endpoints by name", () => {
    if (webComponent === undefined) throw new Error("staging descriptor has no web component");
    expect(webComponent.build).toBe("npm run build --workspace @kiero/web");
    expect(webComponent.artifact).toBe("apps/web/dist");
    expect(webComponent.requiredConfig).toEqual(
      expect.arrayContaining(["VITE_CONVEX_URL", "VITE_GATEWAY_URL"]),
    );
  });

  it("the release workflow injects the gateway URL as a named vars input, never a secret", () => {
    expect(releaseWorkflow).toContain("VITE_GATEWAY_URL: ${{ vars.STAGING_GATEWAY_URL }}");
    expect(releaseWorkflow).toContain("VITE_CONVEX_URL: ${{ vars.STAGING_CONVEX_URL }}");
    // Build inputs are public URLs: a secrets-context VITE_ reference would
    // smuggle a credential-shaped value into the client bundle.
    expect(releaseWorkflow).not.toMatch(/secrets\.[A-Z_]*VITE_/);
  });
});

describe("R8 validation: the static-only Worker validates without a Container", () => {
  it("wrangler 4.130.0 dry-runs the staging env deploy of the assets Worker", () => {
    const out = join(tmpdir(), `kiero-r8-dryrun-${Date.now()}`);
    const run = spawnSync(
      "npx",
      ["wrangler", "deploy", "--dry-run", "--env", "staging", "--outdir", out],
      {
        cwd: webApp,
        encoding: "utf8",
        timeout: 120_000,
        env: { PATH: process.env.PATH ?? "", CI: "true", WRANGLER_SEND_METRICS: "false" },
      },
    );
    expect(run.status).toBe(0);
    const output = `${run.stdout ?? ""}${run.stderr ?? ""}`;
    expect(output).toContain("--dry-run: exiting now");
    expect(output).toContain("Read 3 files from the assets directory");
    // Static-only proof: wrangler itself reports no bindings (and the config
    // has no Container), so validation needs no container image at all.
    expect(output).toContain("No bindings found");
  }, 150_000);

  it("a bare dry-run (no --env) validates the dev default identically", () => {
    const out = join(tmpdir(), `kiero-r8-dryrun-dev-${Date.now()}`);
    const run = spawnSync("npx", ["wrangler", "deploy", "--dry-run", "--outdir", out], {
      cwd: webApp,
      encoding: "utf8",
      timeout: 120_000,
      env: { PATH: process.env.PATH ?? "", CI: "true", WRANGLER_SEND_METRICS: "false" },
    });
    expect(run.status).toBe(0);
  }, 150_000);
});

describe("R8 serving: SPA fallback and /sw.js delivery (local wrangler dev)", () => {
  beforeAll(async () => {
    devServer = await startDevServer();
  }, 90_000);

  afterAll(() => {
    if (devServer !== null) {
      const pid = devServer.process.pid;
      if (pid !== undefined) {
        try {
          // Negative pid = the whole process group (wrangler + workerd).
          process.kill(-pid, "SIGTERM");
        } catch {
          // Already gone; nothing to clean up.
        }
      }
      devServer = null;
    }
  }, 30_000);

  const get = (path: string) => {
    if (devServer === null) throw new Error("dev server not running");
    return fetch(`http://127.0.0.1:${String(devServer.port)}${path}`, {
      signal: AbortSignal.timeout(5000),
      redirect: "manual",
    });
  };

  it("serves the shell at /", async () => {
    const response = await get("/");
    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toContain("text/html");
    expect(await response.text()).toContain(FIXTURE_TITLE);
  });

  for (const route of ["/zrodlo", "/praca", "/co-teraz"]) {
    it(`serves the SPA shell for the direct link ${route}`, async () => {
      const response = await get(route);
      expect(response.status).toBe(200);
      expect(response.headers.get("content-type")).toContain("text/html");
      expect(await response.text()).toContain(FIXTURE_TITLE);
    });
  }

  it("delivers /sw.js as itself, never the SPA shell", async () => {
    const response = await get("/sw.js");
    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toContain("text/javascript");
    expect(await response.text()).toBe(FIXTURE_SW);
  });

  it("delivers a real asset byte-for-byte", async () => {
    const response = await get(`/${FIXTURE_ASSET_NAME}`);
    expect(response.status).toBe(200);
    expect(await response.text()).toBe(FIXTURE_ASSET_BYTES);
  });
});

// ---------------------------------------------------------------------------
// Release-boundary refusals: the exact workflow executable against the
// COMMITTED staging descriptor, with a passing fixture checks report (the
// gate's own sanctioned local-rehearsal input) and a temporary ledger.
// No transport can start in these runs: every case is blocked first.
// ---------------------------------------------------------------------------

interface OutcomeRow {
  component: string;
  outcome: string;
  blockedReason?: string;
  missingConfigNames?: string[];
  observedEnvironmentLabel?: string;
  requiredEnvironmentLabel?: string;
  buildExitCode?: number;
}

function runAdapterWithCommittedDescriptor(env: Record<string, string>) {
  const directory = mkdtempSync(join(tmpdir(), "kiero-r8-release-"));
  const checksReport = join(directory, "checks-report.json");
  const ledger = join(directory, "releases.jsonl");
  const outcomes = join(directory, "deploy-outcomes.json");
  writeFileSync(
    checksReport,
    `${JSON.stringify({
      generatedAtIso: new Date().toISOString(),
      source: "fixture",
      requestedSha: REVISION,
      checksName: CHECKS_JOB_NAME,
      decision: "pass",
      reasons: [],
      observed: [{ name: CHECKS_JOB_NAME, status: "completed", conclusion: "success", headSha: REVISION }],
    })}\n`,
  );
  const run = spawnSync(
    process.execPath,
    [
      adapterCli,
      "--descriptor", stagingDescriptorPath,
      "--revision", REVISION,
      "--checks-report", checksReport,
      "--ledger", ledger,
      "--outcomes", outcomes,
      "--component", "web",
    ],
    {
      cwd: repoRoot,
      encoding: "utf8",
      env: { PATH: process.env.PATH ?? "", ...env },
    },
  );
  const rows = existsSync(outcomes)
    ? ((JSON.parse(readFileSync(outcomes, "utf8")) as { outcomes: OutcomeRow[] }).outcomes)
    : [];
  return { run, rows, ledger };
}

describe("R8 release boundary: missing-endpoint refusal (no transport starts)", () => {
  it("a web build without any endpoint config refuses naming both public URLs", () => {
    const { run, rows } = runAdapterWithCommittedDescriptor({ KIERO_ENVIRONMENT: "staging" });
    expect(run.status).toBe(1);
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({ component: "web", outcome: "blocked", blockedReason: "missing-configuration" });
    expect(rows[0]?.missingConfigNames).toEqual(
      expect.arrayContaining(["VITE_CONVEX_URL", "VITE_GATEWAY_URL"]),
    );
    // Blocked before the build: no build exit code was ever recorded.
    expect(rows[0]?.buildExitCode).toBeUndefined();
  });

  it("missing VITE_GATEWAY_URL alone refuses even with the Convex URL present", () => {
    const { run, rows } = runAdapterWithCommittedDescriptor({
      KIERO_ENVIRONMENT: "staging",
      VITE_CONVEX_URL: "https://example.convex.cloud",
      CLOUDFLARE_API_TOKEN: "not-a-real-token-fixture",
      CLOUDFLARE_ACCOUNT_ID: "not-a-real-id-fixture",
    });
    expect(run.status).toBe(1);
    expect(rows[0]?.blockedReason).toBe("missing-configuration");
    expect(rows[0]?.missingConfigNames).toEqual(["VITE_GATEWAY_URL"]);
    expect(rows[0]?.buildExitCode).toBeUndefined();
  });

  it("missing VITE_CONVEX_URL alone refuses even with the gateway URL present", () => {
    const { run, rows } = runAdapterWithCommittedDescriptor({
      KIERO_ENVIRONMENT: "staging",
      VITE_GATEWAY_URL: "https://example.workers.dev",
      CLOUDFLARE_API_TOKEN: "not-a-real-token-fixture",
      CLOUDFLARE_ACCOUNT_ID: "not-a-real-id-fixture",
    });
    expect(run.status).toBe(1);
    expect(rows[0]?.missingConfigNames).toEqual(["VITE_CONVEX_URL"]);
    expect(rows[0]?.buildExitCode).toBeUndefined();
  });
});

describe("R8 release boundary: wrong-environment refusal", () => {
  it("a staging release run claiming the production label refuses the web component", () => {
    const { run, rows } = runAdapterWithCommittedDescriptor({
      KIERO_ENVIRONMENT: "production",
      VITE_CONVEX_URL: "https://example.convex.cloud",
      VITE_GATEWAY_URL: "https://example.workers.dev",
      CLOUDFLARE_API_TOKEN: "not-a-real-token-fixture",
      CLOUDFLARE_ACCOUNT_ID: "not-a-real-id-fixture",
    });
    expect(run.status).toBe(1);
    expect(rows[0]).toMatchObject({
      component: "web",
      outcome: "blocked",
      blockedReason: "unauthorized-environment",
      observedEnvironmentLabel: "production",
      requiredEnvironmentLabel: "staging",
    });
    expect(rows[0]?.buildExitCode).toBeUndefined();
  });

  it("an absent environment label is unauthorized, not silently accepted", () => {
    const { rows } = runAdapterWithCommittedDescriptor({
      KIERO_ENVIRONMENT: "",
      VITE_CONVEX_URL: "https://example.convex.cloud",
      VITE_GATEWAY_URL: "https://example.workers.dev",
    });
    expect(rows[0]).toMatchObject({
      blockedReason: "unauthorized-environment",
      observedEnvironmentLabel: "(absent)",
    });
  });
});

describe("R8 transport identity: the web component's wrangler-deploy refuses unknown identities", () => {
  // A PATH-shimmed `npx` records the exact deploy invocation and replays a
  // wrangler-shaped output: deterministic and offline, no cloud contact.
  const shimDirectory = mkdtempSync(join(tmpdir(), "kiero-r8-npx-shim-"));
  const shimLog = join(shimDirectory, "npx-calls.jsonl");

  beforeAll(() => {
    const shim = join(shimDirectory, "npx");
    writeFileSync(
      shim,
      `#!/usr/bin/env node
const fs = require("node:fs");
fs.appendFileSync(${JSON.stringify(shimLog)}, JSON.stringify({ argv: process.argv.slice(2), cwd: process.cwd() }) + "\\n");
process.stdout.write(process.env.SHIM_STDOUT ?? "");
process.exit(Number(process.env.SHIM_EXIT ?? "0"));
`,
    );
    chmodSync(shim, 0o755);
  });

  const callTransport = async (shimStdout: string) => {
    const transport = webComponent?.transport;
    if (
      transport?.kind !== "wrangler-deploy" ||
      transport.cwd === undefined ||
      transport.wranglerEnv === undefined ||
      transport.workerName === undefined
    ) {
      throw new Error("staging web component is not a fully-formed wrangler-deploy transport");
    }
    // Imported through a computed specifier: the checked transport modules
    // under infra/release/transports carry no .d.mts (their owning lane
    // declares only the four adapter-facing modules), and adding one there
    // is outside this issue's owned paths.
    const transportUrl = pathToFileURL(
      join(repoRoot, "infra", "release", "transports", "wrangler-deploy.mjs"),
    ).href;
    const transportModule = (await import(/* @vite-ignore */ transportUrl)) as unknown as {
      run: (args: Record<string, unknown>) => { remoteIdentity: { kind: string; id: string; versionId?: string } };
    };
    return transportModule.run({
      transport,
      env: {
        PATH: `${shimDirectory}${delimiter}${process.env.PATH ?? ""}`,
        SHIM_STDOUT: shimStdout,
      },
      cwd: repoRoot,
    });
  };

  it("deploys --env staging in apps/web and claims only the declared worker identity", async () => {
    const result = await callTransport(
      `Deployed ${STAGING_WEB_ORIGIN} (wrangler-shaped fixture output)\nVersion ID: 0123456789abcdef0123456789abcdef\n`,
    );
    expect(result.remoteIdentity).toMatchObject({
      kind: "cloudflare-worker",
      id: "kiero-staging-web",
      versionId: "0123456789abcdef0123456789abcdef",
    });
    const calls = readFileSync(shimLog, "utf8")
      .split("\n")
      .filter((line) => line.trim() !== "")
      .map((line) => JSON.parse(line) as { argv: string[]; cwd: string });
    const last = calls.at(-1);
    expect(last?.argv).toEqual(["wrangler", "deploy", "--env", "staging"]);
    expect(last?.cwd).toBe(join(repoRoot, "apps", "web"));
  });

  it("output that never names the declared worker refuses to claim an identity", async () => {
    await expect(
      callTransport("Deployed some-other-worker (wrangler-shaped fixture output)\nVersion ID: 0123456789abcdef0123456789abcdef\n"),
    ).rejects.toThrow(/refusing to claim identity/);
  });
});
